/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Alert {
    id: bigint;
    sentimentScore: number;
    headline: string;
    relatedSymbols: Array<string>;
    triggeredAt: Time;
    severity: Variant_high_critical_medium;
}
export interface LeaderboardEntry {
    displayName: string;
    accuracyRate: number;
}
export type StockSymbol = string;
export type Time = bigint;
export interface Prediction {
    result: string;
    direction: string;
    stockSymbol: string;
    user: UserID;
    actualOutcome: string;
    aiPrediction: string;
}
export interface QuizResult {
    score: bigint;
    takenAt: Time;
}
export type UserID = Principal;
export interface Holding {
    shares: bigint;
    avgBuyPrice: number;
    symbol: string;
}
export interface Post {
    symbols: Array<string>;
    content: string;
    votes: bigint;
    author: UserID;
    timestamp: Time;
}
export interface LearningProgressView {
    scores: Array<[string, bigint]>;
    lastUpdated: Time;
    completedLessons: bigint;
}
export interface UserProfileView {
    hasPassword: boolean;
    displayName: string;
    predictionAccuracy: number;
    portfolioRef?: bigint;
    quizResults: Array<[string, QuizResult]>;
    lessonsCompleted: bigint;
}
export interface Portfolio {
    totalValue: number;
    holdings: Array<Holding>;
    riskScore: bigint;
}
export interface NewsArticle {
    _id: bigint;
    title: string;
    symbols: Array<string>;
    date: Time;
    marketImpact: bigint;
    sentiment: string;
    score: bigint;
    summary: string;
}
export interface Message {
    content: string;
    sender: UserID;
    timestamp: Time;
}
export interface UserProfileInput {
    displayName: string;
    predictionAccuracy: number;
    portfolioRef?: bigint;
    lessonsCompleted: bigint;
}
export interface Conversation {
    messages: Array<Message>;
    lastUpdated: Time;
}
export interface LearningProgress {
    lastUpdated: Time;
    completedLessons: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_high_critical_medium {
    high = "high",
    critical = "critical",
    medium = "medium"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNewsArticleWithScore(article: NewsArticle): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPost(content: string, symbols: Array<string>): Promise<void>;
    getArticlesByDateRange(startTime: Time, endTime: Time): Promise<Array<NewsArticle>>;
    getArticlesBySentiment(sentiment: string): Promise<Array<NewsArticle>>;
    getArticlesBySymbol(symbol: string): Promise<Array<NewsArticle>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversation(): Promise<Conversation | null>;
    getForumPosts(sortByVotes: boolean): Promise<Array<Post>>;
    getLearningProgress(): Promise<LearningProgressView | null>;
    getMarketAlerts(): Promise<Array<Alert>>;
    getNewsArticle(id: bigint): Promise<NewsArticle | null>;
    getNewsArticles(): Promise<Array<NewsArticle>>;
    getPortfolio(): Promise<Portfolio | null>;
    getPublicLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getPublicMarketAlerts(): Promise<Array<Alert>>;
    getPublicNewsFeed(): Promise<Array<NewsArticle>>;
    getPublicStockList(): Promise<Array<StockSymbol>>;
    getSentimentImpactTimeline(symbol: string): Promise<Array<[Time, bigint]>>;
    getSummaryStatistics(): Promise<{
        negativeCount: bigint;
        positiveCount: bigint;
        neutralCount: bigint;
        averageScore: number;
    }>;
    getTopPosts(): Promise<Array<Post>>;
    getUserPredictions(): Promise<Array<Prediction>>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    initializeNewsDatabase(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profileInput: UserProfileInput): Promise<void>;
    saveLearningProgress(progress: LearningProgress): Promise<void>;
    savePortfolio(portfolio: Portfolio): Promise<void>;
    sendMessage(content: string): Promise<void>;
    setUserPassword(passwordHash: string): Promise<boolean>;
    submitPrediction(prediction: Prediction): Promise<void>;
    upvotePost(index: bigint): Promise<void>;
    verifyUserPassword(passwordHash: string): Promise<boolean>;
}
import type { Alert as _Alert, Conversation as _Conversation, LearningProgressView as _LearningProgressView, NewsArticle as _NewsArticle, Portfolio as _Portfolio, QuizResult as _QuizResult, Time as _Time, UserProfileInput as _UserProfileInput, UserProfileView as _UserProfileView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNewsArticleWithScore(arg0: NewsArticle): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsArticleWithScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsArticleWithScore(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPost(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1);
            return result;
        }
    }
    async getArticlesByDateRange(arg0: Time, arg1: Time): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getArticlesBySentiment(arg0: string): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesBySentiment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesBySentiment(arg0);
            return result;
        }
    }
    async getArticlesBySymbol(arg0: string): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlesBySymbol(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlesBySymbol(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversation(): Promise<Conversation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForumPosts(arg0: boolean): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForumPosts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForumPosts(arg0);
            return result;
        }
    }
    async getLearningProgress(): Promise<LearningProgressView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLearningProgress();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLearningProgress();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketAlerts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketAlerts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticle(arg0: bigint): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticle(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticle(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsArticles(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsArticles();
            return result;
        }
    }
    async getPortfolio(): Promise<Portfolio | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicLeaderboard();
            return result;
        }
    }
    async getPublicMarketAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicMarketAlerts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicMarketAlerts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicNewsFeed(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicNewsFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicNewsFeed();
            return result;
        }
    }
    async getPublicStockList(): Promise<Array<StockSymbol>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicStockList();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicStockList();
            return result;
        }
    }
    async getSentimentImpactTimeline(arg0: string): Promise<Array<[Time, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentimentImpactTimeline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentimentImpactTimeline(arg0);
            return result;
        }
    }
    async getSummaryStatistics(): Promise<{
        negativeCount: bigint;
        positiveCount: bigint;
        neutralCount: bigint;
        averageScore: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryStatistics();
            return result;
        }
    }
    async getTopPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopPosts();
            return result;
        }
    }
    async getUserPredictions(): Promise<Array<Prediction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPredictions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPredictions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeNewsDatabase(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeNewsDatabase();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeNewsDatabase();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfileInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveLearningProgress(arg0: LearningProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLearningProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLearningProgress(arg0);
            return result;
        }
    }
    async savePortfolio(arg0: Portfolio): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePortfolio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePortfolio(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async setUserPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPassword(arg0);
            return result;
        }
    }
    async submitPrediction(arg0: Prediction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrediction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrediction(arg0);
            return result;
        }
    }
    async upvotePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upvotePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upvotePost(arg0);
            return result;
        }
    }
    async verifyUserPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUserPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUserPassword(arg0);
            return result;
        }
    }
}
function from_candid_Alert_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LearningProgressView]): LearningProgressView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Portfolio]): Portfolio | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Conversation]): Conversation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    sentimentScore: number;
    headline: string;
    relatedSymbols: Array<string>;
    triggeredAt: _Time;
    severity: {
        high: null;
    } | {
        critical: null;
    } | {
        medium: null;
    };
}): {
    id: bigint;
    sentimentScore: number;
    headline: string;
    relatedSymbols: Array<string>;
    triggeredAt: Time;
    severity: Variant_high_critical_medium;
} {
    return {
        id: value.id,
        sentimentScore: value.sentimentScore,
        headline: value.headline,
        relatedSymbols: value.relatedSymbols,
        triggeredAt: value.triggeredAt,
        severity: from_candid_variant_n14(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasPassword: boolean;
    displayName: string;
    predictionAccuracy: number;
    portfolioRef: [] | [bigint];
    quizResults: Array<[string, _QuizResult]>;
    lessonsCompleted: bigint;
}): {
    hasPassword: boolean;
    displayName: string;
    predictionAccuracy: number;
    portfolioRef?: bigint;
    quizResults: Array<[string, QuizResult]>;
    lessonsCompleted: bigint;
} {
    return {
        hasPassword: value.hasPassword,
        displayName: value.displayName,
        predictionAccuracy: value.predictionAccuracy,
        portfolioRef: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.portfolioRef)),
        quizResults: value.quizResults,
        lessonsCompleted: value.lessonsCompleted
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Variant_high_critical_medium {
    return "high" in value ? Variant_high_critical_medium.high : "critical" in value ? Variant_high_critical_medium.critical : "medium" in value ? Variant_high_critical_medium.medium : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n12(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfileInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfileInput): _UserProfileInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    predictionAccuracy: number;
    portfolioRef?: bigint;
    lessonsCompleted: bigint;
}): {
    displayName: string;
    predictionAccuracy: number;
    portfolioRef: [] | [bigint];
    lessonsCompleted: bigint;
} {
    return {
        displayName: value.displayName,
        predictionAccuracy: value.predictionAccuracy,
        portfolioRef: value.portfolioRef ? candid_some(value.portfolioRef) : candid_none(),
        lessonsCompleted: value.lessonsCompleted
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
