/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const NewsArticle = IDL.Record({
  '_id' : IDL.Nat,
  'title' : IDL.Text,
  'symbols' : IDL.Vec(IDL.Text),
  'date' : Time,
  'marketImpact' : IDL.Int,
  'sentiment' : IDL.Text,
  'score' : IDL.Int,
  'summary' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizResult = IDL.Record({ 'score' : IDL.Nat, 'takenAt' : Time });
export const UserProfileView = IDL.Record({
  'hasPassword' : IDL.Bool,
  'displayName' : IDL.Text,
  'predictionAccuracy' : IDL.Float64,
  'portfolioRef' : IDL.Opt(IDL.Nat),
  'quizResults' : IDL.Vec(IDL.Tuple(IDL.Text, QuizResult)),
  'lessonsCompleted' : IDL.Nat,
});
export const UserID = IDL.Principal;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'sender' : UserID,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'messages' : IDL.Vec(Message),
  'lastUpdated' : Time,
});
export const Post = IDL.Record({
  'symbols' : IDL.Vec(IDL.Text),
  'content' : IDL.Text,
  'votes' : IDL.Nat,
  'author' : UserID,
  'timestamp' : Time,
});
export const LearningProgressView = IDL.Record({
  'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'lastUpdated' : Time,
  'completedLessons' : IDL.Nat,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'sentimentScore' : IDL.Float64,
  'headline' : IDL.Text,
  'relatedSymbols' : IDL.Vec(IDL.Text),
  'triggeredAt' : Time,
  'severity' : IDL.Variant({
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const Holding = IDL.Record({
  'shares' : IDL.Nat,
  'avgBuyPrice' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'totalValue' : IDL.Float64,
  'holdings' : IDL.Vec(Holding),
  'riskScore' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'accuracyRate' : IDL.Float64,
});
export const StockSymbol = IDL.Text;
export const Prediction = IDL.Record({
  'result' : IDL.Text,
  'direction' : IDL.Text,
  'stockSymbol' : IDL.Text,
  'user' : UserID,
  'actualOutcome' : IDL.Text,
  'aiPrediction' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'displayName' : IDL.Text,
  'predictionAccuracy' : IDL.Float64,
  'portfolioRef' : IDL.Opt(IDL.Nat),
  'lessonsCompleted' : IDL.Nat,
});
export const LearningProgress = IDL.Record({
  'lastUpdated' : Time,
  'completedLessons' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNewsArticleWithScore' : IDL.Func([NewsArticle], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'getArticlesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getArticlesBySentiment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getArticlesBySymbol' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(NewsArticle)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([], [IDL.Opt(Conversation)], ['query']),
  'getForumPosts' : IDL.Func([IDL.Bool], [IDL.Vec(Post)], ['query']),
  'getLearningProgress' : IDL.Func(
      [],
      [IDL.Opt(LearningProgressView)],
      ['query'],
    ),
  'getMarketAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getNewsArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
  'getNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getPortfolio' : IDL.Func([], [IDL.Opt(Portfolio)], ['query']),
  'getPublicLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getPublicMarketAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getPublicNewsFeed' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getPublicStockList' : IDL.Func([], [IDL.Vec(StockSymbol)], ['query']),
  'getSentimentImpactTimeline' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(Time, IDL.Int))],
      ['query'],
    ),
  'getSummaryStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'negativeCount' : IDL.Nat,
          'positiveCount' : IDL.Nat,
          'neutralCount' : IDL.Nat,
          'averageScore' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getTopPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'initializeNewsDatabase' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
  'saveLearningProgress' : IDL.Func([LearningProgress], [], []),
  'savePortfolio' : IDL.Func([Portfolio], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'setUserPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'submitPrediction' : IDL.Func([Prediction], [], []),
  'upvotePost' : IDL.Func([IDL.Nat], [], []),
  'verifyUserPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const NewsArticle = IDL.Record({
    '_id' : IDL.Nat,
    'title' : IDL.Text,
    'symbols' : IDL.Vec(IDL.Text),
    'date' : Time,
    'marketImpact' : IDL.Int,
    'sentiment' : IDL.Text,
    'score' : IDL.Int,
    'summary' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizResult = IDL.Record({ 'score' : IDL.Nat, 'takenAt' : Time });
  const UserProfileView = IDL.Record({
    'hasPassword' : IDL.Bool,
    'displayName' : IDL.Text,
    'predictionAccuracy' : IDL.Float64,
    'portfolioRef' : IDL.Opt(IDL.Nat),
    'quizResults' : IDL.Vec(IDL.Tuple(IDL.Text, QuizResult)),
    'lessonsCompleted' : IDL.Nat,
  });
  const UserID = IDL.Principal;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'sender' : UserID,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'messages' : IDL.Vec(Message),
    'lastUpdated' : Time,
  });
  const Post = IDL.Record({
    'symbols' : IDL.Vec(IDL.Text),
    'content' : IDL.Text,
    'votes' : IDL.Nat,
    'author' : UserID,
    'timestamp' : Time,
  });
  const LearningProgressView = IDL.Record({
    'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'lastUpdated' : Time,
    'completedLessons' : IDL.Nat,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'sentimentScore' : IDL.Float64,
    'headline' : IDL.Text,
    'relatedSymbols' : IDL.Vec(IDL.Text),
    'triggeredAt' : Time,
    'severity' : IDL.Variant({
      'high' : IDL.Null,
      'critical' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const Holding = IDL.Record({
    'shares' : IDL.Nat,
    'avgBuyPrice' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'totalValue' : IDL.Float64,
    'holdings' : IDL.Vec(Holding),
    'riskScore' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'accuracyRate' : IDL.Float64,
  });
  const StockSymbol = IDL.Text;
  const Prediction = IDL.Record({
    'result' : IDL.Text,
    'direction' : IDL.Text,
    'stockSymbol' : IDL.Text,
    'user' : UserID,
    'actualOutcome' : IDL.Text,
    'aiPrediction' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'displayName' : IDL.Text,
    'predictionAccuracy' : IDL.Float64,
    'portfolioRef' : IDL.Opt(IDL.Nat),
    'lessonsCompleted' : IDL.Nat,
  });
  const LearningProgress = IDL.Record({
    'lastUpdated' : Time,
    'completedLessons' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNewsArticleWithScore' : IDL.Func([NewsArticle], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'getArticlesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getArticlesBySentiment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getArticlesBySymbol' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(NewsArticle)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([], [IDL.Opt(Conversation)], ['query']),
    'getForumPosts' : IDL.Func([IDL.Bool], [IDL.Vec(Post)], ['query']),
    'getLearningProgress' : IDL.Func(
        [],
        [IDL.Opt(LearningProgressView)],
        ['query'],
      ),
    'getMarketAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getNewsArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
    'getNewsArticles' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getPortfolio' : IDL.Func([], [IDL.Opt(Portfolio)], ['query']),
    'getPublicLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getPublicMarketAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getPublicNewsFeed' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getPublicStockList' : IDL.Func([], [IDL.Vec(StockSymbol)], ['query']),
    'getSentimentImpactTimeline' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(Time, IDL.Int))],
        ['query'],
      ),
    'getSummaryStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'negativeCount' : IDL.Nat,
            'positiveCount' : IDL.Nat,
            'neutralCount' : IDL.Nat,
            'averageScore' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getTopPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserPredictions' : IDL.Func([], [IDL.Vec(Prediction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'initializeNewsDatabase' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfileInput], [], []),
    'saveLearningProgress' : IDL.Func([LearningProgress], [], []),
    'savePortfolio' : IDL.Func([Portfolio], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'setUserPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'submitPrediction' : IDL.Func([Prediction], [], []),
    'upvotePost' : IDL.Func([IDL.Nat], [], []),
    'verifyUserPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };