/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'sentimentScore' : number,
  'headline' : string,
  'relatedSymbols' : Array<string>,
  'triggeredAt' : Time,
  'severity' : { 'high' : null } |
    { 'critical' : null } |
    { 'medium' : null },
}
export interface Conversation {
  'messages' : Array<Message>,
  'lastUpdated' : Time,
}
export interface Holding {
  'shares' : bigint,
  'avgBuyPrice' : number,
  'symbol' : string,
}
export interface LeaderboardEntry {
  'displayName' : string,
  'accuracyRate' : number,
}
export interface LearningProgress {
  'lastUpdated' : Time,
  'completedLessons' : bigint,
}
export interface LearningProgressView {
  'scores' : Array<[string, bigint]>,
  'lastUpdated' : Time,
  'completedLessons' : bigint,
}
export interface Message {
  'content' : string,
  'sender' : UserID,
  'timestamp' : Time,
}
export interface NewsArticle {
  '_id' : bigint,
  'title' : string,
  'symbols' : Array<string>,
  'date' : Time,
  'marketImpact' : bigint,
  'sentiment' : string,
  'score' : bigint,
  'summary' : string,
}
export interface Portfolio {
  'totalValue' : number,
  'holdings' : Array<Holding>,
  'riskScore' : bigint,
}
export interface Post {
  'symbols' : Array<string>,
  'content' : string,
  'votes' : bigint,
  'author' : UserID,
  'timestamp' : Time,
}
export interface Prediction {
  'result' : string,
  'direction' : string,
  'stockSymbol' : string,
  'user' : UserID,
  'actualOutcome' : string,
  'aiPrediction' : string,
}
export interface QuizResult { 'score' : bigint, 'takenAt' : Time }
export type StockSymbol = string;
export type Time = bigint;
export type UserID = Principal;
export interface UserProfileInput {
  'displayName' : string,
  'predictionAccuracy' : number,
  'portfolioRef' : [] | [bigint],
  'lessonsCompleted' : bigint,
}
export interface UserProfileView {
  'hasPassword' : boolean,
  'displayName' : string,
  'predictionAccuracy' : number,
  'portfolioRef' : [] | [bigint],
  'quizResults' : Array<[string, QuizResult]>,
  'lessonsCompleted' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNewsArticle' : ActorMethod<[NewsArticle], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, Array<string>], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[], [] | [Conversation]>,
  'getForumPosts' : ActorMethod<[boolean], Array<Post>>,
  'getLearningProgress' : ActorMethod<[], [] | [LearningProgressView]>,
  'getMarketAlerts' : ActorMethod<[], Array<Alert>>,
  'getNewsArticle' : ActorMethod<[bigint], [] | [NewsArticle]>,
  'getNewsArticles' : ActorMethod<[], Array<NewsArticle>>,
  'getPortfolio' : ActorMethod<[], [] | [Portfolio]>,
  'getPublicLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getPublicMarketAlerts' : ActorMethod<[], Array<Alert>>,
  'getPublicNewsFeed' : ActorMethod<[], Array<NewsArticle>>,
  'getPublicStockList' : ActorMethod<[], Array<StockSymbol>>,
  'getTopPosts' : ActorMethod<[], Array<Post>>,
  'getUserPredictions' : ActorMethod<[], Array<Prediction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileInput], undefined>,
  'saveLearningProgress' : ActorMethod<[LearningProgress], undefined>,
  'savePortfolio' : ActorMethod<[Portfolio], undefined>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'setUserPassword' : ActorMethod<[string], boolean>,
  'submitPrediction' : ActorMethod<[Prediction], undefined>,
  'upvotePost' : ActorMethod<[bigint], undefined>,
  'verifyUserPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];